name: PR Workflow

on:
  pull_request:
    types: [closed]

jobs:
  check_pr_body:
    runs-on: ubuntu-latest
    outputs:
      pr_type: ${{ steps.check_pr_body.outputs.pr_type }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Check PR body
        id: check_pr_body
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prBody = context.payload.pull_request.body;
            let prType = 'UNKNOWN';
            
            if (prBody.includes('- [x] MAIN')) {
              prType = 'MAIN';
            } else if (prBody.includes('- [x] DEV-USER')) {
              prType = 'DEV-USER';
            } else if (prBody.includes('- [x] DEV-ADMIN')) {
              prType = 'DEV-ADMIN';
            } else if (prBody.includes('- [x] DEV-SERVER')) {
              prType = 'DEV-SERVER';
            }
            
            core.setOutput('pr_type', prType);

  trigger_jenkins:
    needs: check_pr_body
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Pipeline
        env:
          PR_TYPE: ${{ needs.check_pr_body.outputs.pr_type }}
        run: |
          if [ "$PR_TYPE" != "UNKNOWN" ]; then
            JENKINS_JOB=""
            case "$PR_TYPE" in
              "MAIN")
                JENKINS_JOB="DEPLOY_REST32"
                ;;
              "DEV-USER")
                JENKINS_JOB="DEV_REST32USER"
                ;;
              "DEV-ADMIN")
                JENKINS_JOB="DEV_REST32ADMIN"
                ;;
              "DEV-SERVER")
                JENKINS_JOB="DEV_REST32SERVER"
                ;;
            esac
            
            if [ -n "$JENKINS_JOB" ]; then
              curl -X POST \
                --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
                "${{ secrets.JENKINS_URL }}/job/${JENKINS_JOB}/build"
            else
              echo "No matching Jenkins job found for PR type: $PR_TYPE"
            fi
          else
            echo "No valid PR type selected"
          fi